# Generated by Django 2.1 on 2018-10-30 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181030_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='s_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
