# Generated by Django 2.1 on 2018-10-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20181030_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='s_id',
        ),
    ]
