# Generated by Django 2.1 on 2018-10-30 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20181030_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
