# Generated by Django 2.1 on 2018-10-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_product_p_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
