# Generated by Django 2.1 on 2018-11-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20181104_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
