# Generated by Django 2.1 on 2018-11-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
