# Generated by Django 2.1 on 2018-11-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20181106_1219'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyer',
            table='buyer',
        ),
    ]
