# Generated by Django 2.1 on 2018-11-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20181106_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='b_Email',
            new_name='b_email',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='s_Email',
            new_name='s_email',
        ),
    ]
