# Generated by Django 2.1 on 2018-11-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20181106_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='id',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='b_email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
