# Generated by Django 2.1 on 2018-11-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20181106_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
