# Generated by Django 2.1 on 2018-11-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20181106_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bid',
            field=models.ForeignKey(db_column='b_email', on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer'),
        ),
    ]
