# Generated by Django 2.1 on 2018-11-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20181106_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer'),
        ),
    ]
