# Generated by Django 2.1 on 2018-11-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_remove_cart_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer'),
            preserve_default=False,
        ),
    ]
