# Generated by Django 2.1 on 2018-11-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_cart_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.product'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('pid', 'bid')},
        ),
    ]
