# Generated by Django 2.1 on 2018-11-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_auto_20181106_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='s_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.seller'),
            preserve_default=False,
        ),
    ]
