# Generated by Django 2.1 on 2018-11-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_product_s_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
