# Generated by Django 2.1 on 2018-11-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_auto_20181106_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.seller')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('bid', 'pid', 'sid')},
        ),
    ]
