# Generated by Django 2.1 on 2018-11-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_product_stock'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
