# Generated by Django 2.1 on 2018-11-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20181108_1731'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order1',
        ),
    ]
