# Generated by Django 2.1 on 2018-11-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20181108_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=10)),
                ('pincode', models.IntegerField()),
                ('name_on_card', models.CharField(max_length=50)),
                ('credit_card_number', models.CharField(max_length=20)),
                ('exp_month', models.CharField(max_length=10)),
                ('exp_year', models.IntegerField()),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.buyer'),
        ),
    ]
