# Generated by Django 2.1 on 2018-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_auto_20181127_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
