# Generated by Django 2.1 on 2018-11-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_auto_20181129_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='credit_card_number',
            new_name='ccnum',
        ),
    ]
