# Generated by Django 2.1 on 2018-12-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_auto_20181212_1354'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
