# Generated by Django 2.1 on 2018-12-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_auto_20181213_1242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
